---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-zayac
  namespace: {{ .Values.namespace.name }}
  labels:
    app: app-zayac
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app-zayac
  template:
    metadata:
      labels:
        app: app-zayac
    spec:
      containers:
        - name: app-zayac
          image: {{ .Values.image | quote }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: 80
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: 80
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

...
