---

replicaCount: 6

namespace:
  name: app-diplom

image: nginx:1.30.5-alpine

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

probes:
  liveness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    path: /
    initialDelaySeconds: 3
    periodSeconds: 5

resourceQuota:
  enabled: true
  hard:
    requests.cpu: "1"
    requests.memory: "512Mi"
    limits.cpu: "2"
    limits.memory: "1Gi"
    pods: "10"

...