---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-zayac
  namespace: app-diplom

spec:
  replicas: 6
  selector:
    matchLabels:
      app: app-zayac
  template:
    metadata:
      labels:
        app: app-zayac
    spec:
      containers:
        - name: app-zayac
          image: ${APP_IMAGE}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5

...
